### ISSUE TITLE
Preview outputs fine but when send a test tweet, cannot read property "0.0" form undefined

### ISSUE THREAD

**Issue by majestique** [zachwhalen/ssbot#15]
When I send a test tweet, I'm getting this error:

![image](https://user-images.githubusercontent.com/19336285/64756193-e9b28900-d4e2-11e9-8484-382d1d1cf51f.png)

Any idea why?

**Comment by Zuescho** [comment]
I have the same problem no idea what i did wrong.

**Comment by j2l** [comment]
I have the same issue.
Did you find a fix?

**Comment by wormcurious** [comment]
i'm having this problem too!

**Comment by wormcurious** [comment]
For what it's worth, I switched to version 0.5.2 and it worked just fine

**Comment by walinchus** [comment]
I am having this issue as well.

**Comment by majestique** [comment]
The solution for me was to update to the latest version, I was on version .4 then switched to version .6 and it worked fine.
